name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight UTC on the first day of each month
  workflow_dispatch: # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Fork Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.SYNC_PAT }}
        persist-credentials: false

    - name: Add Upstream Remote
      run: |
        git remote add upstream https://github.com/AzureAD/microsoft-authentication-library-for-dotnet.git
        git fetch upstream

    - name: Sync Fork with Upstream
      run: |
        # Check if the branch is already up to date
        git checkout main
        git fetch upstream
        if git merge-base --is-ancestor upstream/main main; then
          echo "Branch is already up to date."
          exit 0
        fi

        # Try fast-forward merge
        git merge upstream/main --ff-only || {
          echo "Fast-forward merge failed. Check for unrelated histories or conflicts.";
          exit 1;
        }

        # Push updates to the fork
        git push origin main
